# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0004_auto_20170311_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='D:\\prj\\skyenv\\s-cool-project\\sky\\mediano-img.jpg', upload_to='D:\\prj\\skyenv\\s-cool-project\\sky\\media'),
        ),
    ]
