# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0005_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='D:\\prj\\skyenv\\s-cool-project\\sky\\media/no-img.jpg', upload_to='D:\\prj\\skyenv\\s-cool-project\\sky\\media'),
        ),
    ]
