# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0006_auto_20170313_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='\no-img.jpg', upload_to=''),
        ),
    ]
