# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0009_auto_20170313_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='site',
            field=models.URLField(null=True),
        ),
    ]
