# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snow', '0010_userprofile_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_status', models.CharField(choices=[('E', 'Empty'), ('A', 'Asked'), ('G', 'Granted'), ('D', 'Delayed'), ('B', 'Blocked')], default='E', max_length=1)),
                ('expert_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_status', models.CharField(choices=[('E', 'Empty'), ('A', 'Asked'), ('G', 'Granted'), ('D', 'Delayed'), ('B', 'Blocked')], default='E', max_length=1)),
                ('tutor_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=smartfields.fields.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
