# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0011_auto_20170318_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_status',
            field=models.CharField(choices=[('S', 'Student'), ('E', 'Expert'), ('T', 'Tutor')], default='S', max_length=1),
        ),
    ]
