# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0012_userprofile_last_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertstatus',
            old_name='expert_date',
            new_name='add_date',
        ),
        migrations.RenameField(
            model_name='expertstatus',
            old_name='expert_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tutorstatus',
            old_name='tutor_date',
            new_name='add_date',
        ),
        migrations.RenameField(
            model_name='tutorstatus',
            old_name='tutor_status',
            new_name='status',
        ),
    ]
