# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snow', '0013_auto_20170318_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slides', models.URLField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_0', models.BooleanField(default=False)),
                ('out_0', models.BooleanField(default=False)),
                ('in_1', models.BooleanField(default=False)),
                ('out_1', models.BooleanField(default=False)),
                ('in_2', models.BooleanField(default=False)),
                ('out_2', models.BooleanField(default=False)),
                ('in_3', models.BooleanField(default=False)),
                ('out_3', models.BooleanField(default=False)),
                ('in_4', models.BooleanField(default=False)),
                ('out_4', models.BooleanField(default=False)),
                ('in_5', models.BooleanField(default=False)),
                ('out_5', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snow.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(choices=[('0', 'Digest'), ('1', 'N1'), ('2', 'N2'), ('3', 'N3'), ('4', 'N4'), ('5', 'N5')], default='0', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snow.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_out', models.CharField(choices=[('0', 'IN'), ('1', 'OUT')], default='0', max_length=1)),
                ('number', models.CharField(choices=[('1', 'N1'), ('2', 'N2'), ('3', 'N3'), ('4', 'N4'), ('5', 'N5')], default='0', max_length=1)),
                ('picture', smartfields.fields.ImageField(null=True, upload_to='')),
                ('txt', models.TextField(max_length=300)),
                ('answer', models.IntegerField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snow.Lecture')),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
