# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0016_lecture_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='txt',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
