# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0017_auto_20170327_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
