# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0018_examrecord_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
