# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 13:52
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0020_auto_20170401_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=smartfields.fields.FileField(null=True, upload_to=''),
        ),
    ]
