# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0021_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='final_try_used',
            field=models.BooleanField(default=False),
        ),
    ]
