# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0022_examrecord_final_try_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='kw_after',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='kw_before',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
