# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0023_auto_20170406_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
