# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0025_auto_20170414_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.FloatField(default=90),
        ),
    ]
