# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 17:34
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0026_auto_20170416_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
