# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0027_auto_20170416_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lat',
            field=models.FloatField(default=59),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lng',
            field=models.FloatField(default=30),
        ),
    ]
